package keittokirja.test;
// Generated by ComTest BEGIN
import java.util.ArrayList;
import static org.junit.Assert.*;
import org.junit.*;
import keittokirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.24 09:44:52 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class AineetTest {



  // Generated by ComTest BEGIN
  /** testLisaaAine39 */
  @Test
  public void testLisaaAine39() {    // Aineet: 39
    Aineet aineet = new Aineet(); 
    Aine aine1 = new Aine("peruna"); 
    Aine aine2 = new Aine("pottu"); 
    aineet.lisaaAine(aine1); 
    assertEquals("From: Aineet line: 46", 1, aineet.getLkm()); 
    aineet.lisaaAine(aine2); 
    assertEquals("From: Aineet line: 49", 2, aineet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTallenna108 */
  @Test
  public void testTallenna108() {    // Aineet: 108
    Aineet aineet1 = new Aineet(); 
    Aine peruna1 = new Aine("peruna"); 
    peruna1.rekisteroi(); 
    aineet1.lisaaAine(peruna1); 
    Aineet.setTiedostoSijainti("tiedostoTestit/aineetTesti.dat"); 
    aineet1.tallenna(); 
    assertEquals("From: Aineet line: 115", 1, aineet1.getLkm()); 
    aineet1.lueTiedosto(); 
    assertEquals("From: Aineet line: 117", 2, aineet1.getLkm()); 
  } // Generated by ComTest END
}