package keittokirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import keittokirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.24 09:45:32 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReseptiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi54 */
  @Test
  public void testRekisteroi54() {    // Resepti: 54
    Resepti pyttis = new Resepti(); 
    Resepti lasa = new Resepti(); 
    assertEquals("From: Resepti line: 57", 2, pyttis.rekisteroi());  //koska jostain syystä toString testataan ensin ja se kerkeää ottamaan
    assertEquals("From: Resepti line: 58", 3, lasa.rekisteroi());  //staattisen seuraavaId 1
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString123 */
  @Test
  public void testToString123() {    // Resepti: 123
    Resepti lasagne = new Resepti(); 
    lasagne.parse("  1 |  Pyttipannu  |   Pilko perunat yms   | 20 minuuttia |  www.k-ruoka.com "); 
    assertEquals("From: Resepti line: 126", true, lasagne.toString().startsWith("1|Pyttipannu|Pilko"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse156 */
  @Test
  public void testParse156() {    // Resepti: 156
    Resepti lasagne = new Resepti(); 
    lasagne.parse("  1 | Pyttipannu |Pilko perunat yms | 20 minuuttia | www.k-ruoka.com"); 
    assertEquals("From: Resepti line: 159", 1, lasagne.getReseptinId()); 
    assertEquals("From: Resepti line: 160", true, lasagne.toString().startsWith("1|Pyttipannu|Pilko"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    lasagne.rekisteroi(); 
    int n = lasagne.getReseptinId(); 
    lasagne.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    lasagne.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Resepti line: 166", n+20+1, lasagne.getReseptinId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAsetaTiedot211 */
  @Test
  public void testAsetaTiedot211() {    // Resepti: 211
    Resepti pyttipannu = new Resepti(); 
    pyttipannu.asetaTiedot("pitsa", "leivo", "60min", "internetti"); 
    assertEquals("From: Resepti line: 214", "pitsa", pyttipannu.getNimi()); 
  } // Generated by ComTest END
}